### ISSUE TITLE
connect-history-api-fallback doesn't work with gulp-connect developer server

### ISSUE THREAD

**Issue by zhekaus** [bripkens/connect-history-api-fallback#10]
I’m trying to use it with Gulp like this:
var gulp = require('gulp'),
connect = require('gulp-connect'),
historyApiFallback = require('connect-history-api-fallback');

gulp.task('server', function() {
	connect.server({
		root: 'app',
		livereload: true,
		middleware: function(connect, opt) {
			return [ historyApiFallback ];
		}
	});
});

However, the server http://localhost:8080/ gives no response. No errors in the terminal, merely get timeout in browser.
When I remove middleware like bellow, everything is perfect:
gulp.task('server', function() {
	connect.server({
		root: 'app',
		livereload: true
	});
});

**Comment by bripkens** [comment]
Please take note of the changed API since `v1.0.0`. The middleware is no longer exported, but needs to be explicitly created.

See https://github.com/bripkens/connect-history-api-fallback#options

**Comment by aceofspades** [comment]
This did it for me:

```javascript

var history = require('connect-history-api-fallback');

gulp.task('connect', function () {
  connect.server({
    root: ['dist'],
    port: config.port,
    base: config.devBaseUrl,
    livereload: true,
    middleware: function(connect, opt) {
      return [
        history({})
      ]
    }
  });
});


```

**Comment by ecohort** [comment]
Thanks!!

`        middleware: function (connect, opt) {
          return [ historyApiFallback({}) ];
        }`
