### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by web2style** [bripkens/connect-history-api-fallback#11]
Hello. Thank you for the great module! You can add the snippet from [this stackoverflow answer](http://stackoverflow.com/a/30711530) to the README.

**Comment by bripkens** [comment]
Hi,

unfortunately I cannot provide usage examples for every kind of middleware-aware system. Libraries like *browserSync* should explain how to use middleware. `connect-history-api-fallback` has usage examples for express and connect in its README. This should be sufficient for most users.
