### ISSUE TITLE
Middleware only redirecting one level deep

### ISSUE THREAD

**Issue by joshuarh** [bripkens/connect-history-api-fallback#12]
So, I expect I'm missing something here. I'm using the middleware with the default settings, in conjunction with `gulp` and `browser-sync`, to power an AngularJS app on my local machine. It works great for some routes but I can't seem to get it to work for routes more than 1 level deep.

For example: `http://localhost/users` will work, but `http://localhost/users/1` redirects back to `/users` and I lose the `1`.

I have the app running on another server where the app works properly, so I'm sure that my Angular routing is set up correctly and there's no redirection happening within the app.

Any suggestions as to where I might be going wrong here? Here's my gulp task if it helps. Most of the config is passed in but I don't think it would be affecting the middleware.

```
browserSync = require 'browser-sync'
history = require 'connect-history-api-fallback'

module.exports = (gulp, ui, config, $) ->
  ->
    browser = config["#{ ui.id }Browser"] = browserSync.create()

    browser.init
      server:
        baseDir: ui.paths.src.dir

      # Support Angular's HTML5 Mode.
      middleware: [ history() ]

      host: config.host
      port: ui.port
      notify: false
      ui: false
```

**Comment by bripkens** [comment]
Interesting issue. You can start debugging this issue by enabling logging via the `verbose` option:

```javascript
history({
  verbose: true
})
```

This will print redirect reasons to the console.

**Comment by joshuarh** [comment]
Thanks @bripkens. I did try this and this is the relevant line that I get:

`Rewriting GET /practice/1 to /index.html`

Not sure where to go from there, however..

**Comment by bripkens** [comment]
This is the correct behavior for the history API fallback. See the following section from the README.

> - The request is a GET request
> - which accepts text/html,
> - is not a direct file request, i.e. the requested path does not contain a . (DOT) character and
> - does not match a pattern provided in options.rewrites (see options below)

**Comment by joshuarh** [comment]
Right, that makes sense.

What I'm wondering is, given this behavior, why `/practice` is preserved but `/practice/1` is not, and if there's anything I can do with this library to preserve the rest of the path. Any thoughts about that?

**Comment by joshuarh** [comment]
So, I took a look at my S3 rewrite rules as I've getting the desired behavior there. 

```
<RoutingRules>
    <RoutingRule>
        <Condition>
            <HttpErrorCodeReturnedEquals>403</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
            <HostName>practice-staging.pollinate.life</HostName>
            <ReplaceKeyPrefixWith>#/</ReplaceKeyPrefixWith>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```

So I'm realizing that what I'm asking for is that I would like `/practice/1` to redirect to `/#/practice/1`. 

Is that out of the scope of this library or is there configuration I can pass to get that same behavior?

**Comment by joshuarh** [comment]
I'm going to close this out, on investigating this further I don't think it has probably has much to do with this middleware. I figured out the correct rewrite rule, but it's still not working. Probably something with my setup. Thanks!

**Comment by joshuarh** [comment]
Sure enough, this was some routing code I had in my Angular app. Sorry about that.
