### ISSUE TITLE
URL with embedded URL - Issue with "://"

### ISSUE THREAD

**Issue by marcosmartinezromero** [bripkens/connect-history-api-fallback#13]
Hello,

I am trying to use this plugin with URLs that contain another URL to identify a particular object, such as:

http://localhost:4200/elements/edit/http://example.org/1, where "http://example.org/1" is an identifier of an object in my domain.

I am using this configuration:
```
historyApiFallback({
   verbose: true,
   rewrites: [
      {
         from: /^.*\/elements\/edit\/.*$/,
         to: function(context) {
            return '/#/';
         }
      }
    ]
});
```
When trying lo load the previous URL, the log shows the message “Rewriting GET /elements/edit/https://example.org/1/ to /#/”, which seems to be correct. However, it looks like the rewriting is not doing anything because the browser returns a white page with the “Cannot GET…” message.

I have realized that the problem is the “://” substring. If this substring is removed from the second URL (e.g., trying to get http://localhost:4200/edit/example.org/1) the behavior is correct.

Is there any way to solve this issue?

**Comment by bripkens** [comment]
Hey Marcos,

I suppose you have a route registered for `/`, but probably not for `/#/`? This would be a common use case and absolutely right. Normally, the part after the `#` is not transferred to the server, but due to the rewrite rule it kind of is.

Can you try changing the rewrite rule to `/`?

**Comment by marcosmartinezromero** [comment]
You are right. However, I changed the rewrite rule to / and still have the same problem. 
The log shows: 
"Rewriting GET /elements/edit/http://example.org/1 to /" 
but the browser returns the message:
"Cannot GET /elements/edit/http://example.org/1/".

**Comment by bripkens** [comment]
This is correct behavior. The browser is not meant to see the redirect as it is internal to the server. Meaning: It is kind of similar to an Apache rewrite rule or proxy configurations. But the message `Cannot GET…` looks like the automatically generated express message for 404s.

Is you app open source by any chance so that I can inspect the route configuration? If not, maybe you can post your route configuration? Without this, debugging is very hard.

**Comment by marcosmartinezromero** [comment]
Hi Ben,

Currently the project is not open source, but here is the fragment of the route configuration that is relevant for this discussion:

```
angularApp.config(function ($routeProvider, $locationProvider) {
    $routeProvider
        .when('/', {
            templateUrl: 'views/dashboard.html',
            controller: 'DashboardController'
        })
        .when('/elements/edit/:id*', {
            templateUrl: 'views/create-element.html',
            controller: 'CreateElementController'
        })
        // Other routes...
        .otherwise({
            redirectTo: '/'
        });
    $locationProvider.html5Mode(true);
});
```
Have you ever tried to use this plugin to rewrite URLs with embedded URLs? Do you have any example code that I can take a look at?

Thanks for your help and, of course, for maintaining this great plugin!

**Comment by bripkens** [comment]
Embedded URLs should work as long as they are properly URL encoded. Could you also paste your express route and middleware config?

**Comment by marcosmartinezromero** [comment]
I was trying to use gulp-connect with the following configuration:

```
gulp.task('server', function() {
    connect.server({
        root: 'app',
        port: 4200,
        livereload: true,
        middleware: function(connect, opt) {
            return [historyApiFallback({
                verbose: true,
                rewrites: [
                    {
                        from: /^.*\/elements\/edit\/.*$/,
                        to: function(context) {
                            return '/';
                        }
                    }
                ]
            })];
        }
    })
});
```
Note that the rewriting rule shown above ('/') is just for testing purposes.

**Comment by marcosmartinezromero** [comment]
It looks like this is a URL encoding problem. When using the $locationProvider.html5Mode(true), the URL shown in the browser is not encoded (http://localhost:4200/elements/edit/http://example.org/1), so if I refresh the page, the middleware receives a unencoded URL, which is not working. When entering http://localhost:4200/elements/edit/http%3A%2F%2Fexample.org%2F1 everything works fine.

**Comment by bripkens** [comment]
Glad to hear that! Does this mean that we can close the issue?

**Comment by marcosmartinezromero** [comment]
Yes, thanks.
