### ISSUE TITLE
Question: How to properly rewrite URLs?

### ISSUE THREAD

**Issue by afgallo** [bripkens/connect-history-api-fallback#16]
Hi,

I'm using this library which works really well on my JavaScript single page application. I've got the code below to do my rewrites. As you can see, all I'm doing is removing the first part of the url path so my static assets get served appropriately from index.html. I must admit I feel embarrassed as it seems am repeating myself quite a lot. I think I'm missing a regular expression that can deal with that in a more elegant way. Another requirement that just came up is that I'll have the first part of the url as a dynamic string i.e. /*john*/edit or /*mary*/edit. Not sure how to do the rewrite in this case?

            {
                from: /^\/tags\/js\/.*$/,
                to: function (context) {
                    return context.parsedUrl.pathname.replace('/tags', '');
                }
            },
            {
                from: /^\/tracks\/js\/.*$/,
                to: function (context) {
                    return context.parsedUrl.pathname.replace('/tracks', '');
                }
            },
            {
                from: /^\/tags\/css\/.*$/,
                to: function (context) {
                    return context.parsedUrl.pathname.replace('/tags', '');
                }
            },
            {
                from: /^\/tracks\/css\/.*$/,
                to: function (context) {
                    return context.parsedUrl.pathname.replace('/tracks', '');
                }
            },

**Comment by bripkens** [comment]
Why do you need rewrite rules for all these paths? JavaScript and CSS files should not be subject to redirects due to the rule

> is not a direct file request, i.e. the requested path does not contain a . (DOT) character

**Comment by afgallo** [comment]
I saw that rule but it doesn't work for me - I've got routes that are more than one level deep:

If I browse to domain.com it works!
If I browse to domain.com/page it also works!
If I browse to domain.com/another/page it doesn't :(

**Comment by bripkens** [comment]
You could leverage the regex match object. This object is provided via `context.match`. Here is an example from the Node.js REPL:

```
> '/tracks/Js/foobar'.match(/^(.*?)\/(js|css)\/(.*)$/i)
[ '/tracks/Js/foobar',
  '/tracks',
  'Js',
  'foobar',
  index: 0,
  input: '/tracks/Js/foobar' ]
```

This means that you could use a regex as shown above and use the match object in the `to`  function as follows:

```javascript
{
    from: /^(.*?)\/(js|css)\/(.*)$/i,
    to: function (context) {
        return context.match[1] + '/' + context.match[3];
    }
}
```

Does this work out for you?

**Comment by bripkens** [comment]
Sorry, I just noticed that you want to strip the prefix for static resources. You could use a similar strategy as shown above with minor changes. The match contains all the information that you need to do this with one rewrite rule.

Hope this helps!

**Comment by afgallo** [comment]
Yeah, the only thing I need is to strip out the first part of the path in case it the url but only when the url path is something like site.com/one/two. I'll give the match object a try ... my regex skills sux tho :(

**Comment by bripkens** [comment]
Can this be closed?

**Comment by afgallo** [comment]
Yes please

**Comment by ajaysourcedigital** [comment]
@afgallo  were you able to solve this ?
