### ISSUE TITLE
Fix dots in URL not being rewritten

### ISSUE THREAD

**Issue by adambuczynski** [bripkens/connect-history-api-fallback#17]
I have a problem with some of my URL's containing a JWT. JWT's have a dot in them, and it's currently causing my URL's not to get rewritten.

The culprit are these lines https://github.com/bripkens/connect-history-api-fallback/blob/master/lib/index.js#L59-L67

I understand they are in there for filenames, but perhaps the check can be made a bit better, like test if the dot is in the last 5 characters of the url, and then assume it's a file. Or actually check if the file exists.

Url's like this should still get rewritten:

http://localhost:8080/email/verify/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU2YTA1NjMwMjEyNTEzMDcxYzhkZjk5ZSIsImlhdCI6MTQ1NDAyNzU3NywiZXhwIjoxNDU0MjAwMzc3LCJhdWQiOiJodHRwOi8vYm9va2luZ3Byby5uei9hcHAiLCJpc3MiOiJodHRwOi8vYm9va2luZ3Byby5uei9hcGkifQ.VaTeu7ZxepyOiHI3DtFFw0iqzBY7lzVa22lfQKxRsHM

**Comment by adambuczynski** [comment]
As a workaround, I've resorted to write my own simple middleware. Instead of filtering out what is the SPA, I am first using the `serve-static` middleware to serve all static files, and then my own middleware to reroute all the rest to the SPA `index.html`:

```js
function(req, res, next) {
  req.url = '/index.html';
  next();
}
```

This does the trick for me.

**Comment by bripkens** [comment]
You could use the rewrites option ([docs](https://github.com/bripkens/connect-history-api-fallback#rewrites)) to route everything under `/email` to the URL received, i.e. do not actually change the URL. This way the middleware will only notice that a user-defined routing mechanism was used and stop the fallback mechanism.

**Comment by adambuczynski** [comment]
I have several URL's that can contain a dot though, and I don't want to have to maintain the serve script whenever I add a new one, so I'll use my work around as a solution for now.

Feel free to close the issue if you don't want to address this use case.

**Comment by bripkens** [comment]
Okay, thanks.
