### ISSUE TITLE
Nested routes with / not working

### ISSUE THREAD

**Issue by CreativeManix** [bripkens/connect-history-api-fallback#19]
If the nested route has / then it is not working when I request to the nested route directly.

But React-router works with /

I am not sure if this is a issue, please investigate.

**Comment by bripkens** [comment]
This is a bit too vague to work on. Can you provide a failing test case to reproduce this issue? See the following test case for a test example:

https://github.com/bripkens/connect-history-api-fallback/blob/ba0f49cc69af15a385cdcd73054a2037a48886a2/test/index_test.js#L53-L61

**Comment by bripkens** [comment]
I see you cross posted this issue to various projects:

https://github.com/davezuko/koa-connect-history-api-fallback/issues/2
https://github.com/davezuko/react-redux-starter-kit/issues/627#issuecomment-192297850

**Comment by CreativeManix** [comment]
Sorry that was by mistake.

however I was testing "react-slingshot" where this module is used. and I had the same issue.

**Comment by bripkens** [comment]
Unfortunately, URL handling involves some many components, especially when SPAs are involved, that it is impossible to debug issues with so little information. If you require help, I need a test case to verify the behavior of the library against.
