### ISSUE TITLE
Option to rewrite only if original file not found

### ISSUE THREAD

**Issue by NateRedding** [bripkens/connect-history-api-fallback#24]
My 'Single Page Application' is actually split into a few smaller 'Single Page Application's. As such, I need to specify rewrite rules so that I can redirect to the appropriate index.html file. For example:

```
        historyApiFallback({
          rewrites: [
            { from: /\/app\/login/, to: '/app/login/index.html'},
            { from: /\/app\/membercenter/, to: '/app/membercenter/index.html'},
            { from: /\/app\/knowledgebase/, to: '/app/knowledgebase/index.html'}
          ]
        })
```

However, when I do this, it loads the 'index.html' file (whichever it may be) instead of loading files that actually exist at other sub paths. For example:

`/app/login/app.js`

Is there a way to make it only follow the rewrite rules if the original file is not found? An option, perhaps? Or, maybe specifying the rewrites as I have done above is the wrong approach and instead maybe there is a way to add multiple indexes? Something like:

```
index: {
  '/app/login': '/app/login/index.html',
  '/app/membercenter': '/app/membercenter/index.html',
  '/app/knowledgebase': '/app/knowledgebase/index.html'
}
```

Any suggestions?

**Comment by NateRedding** [comment]
I am also quite possibly willing to submit a PR if desired.

**Comment by bripkens** [comment]
Hey @NateRedding,

thanks for this detailed issue! I can see why this is confusing. This middleware evaluates the `dot` rule after the `rewrite` rule.

To support your use case, this middleware has the option to specify a `function` to define the rewrite target. I added a test to the repository with a simple rewrite rule implementation. You should be able to adapt it to your use case:

https://github.com/bripkens/connect-history-api-fallback/blob/a43ea0803d28239a63c8bec6c9ae021ec26a4b3c/test/index_test.js#L222-L227

Hope this helps.

**Comment by NateRedding** [comment]
I resolved my problem by writing my own middleware function that does the rewrites as I need them. I was hoping to use connect-history-api-fallback to avoid writing that custom function and keep things a little cleaner. I don't particularly see a reason to use it if I still have to write a custom function.

Oh well - not a huge deal. Thanks for taking a look and providing the example - I truly appreciate it! Please close the issue if you desire.
