### ISSUE TITLE
Option to allow for dots in url

### ISSUE THREAD

**Issue by jcubic** [bripkens/connect-history-api-fallback#27]
I have angular app that have urls like:

/app/apache/1.0.2/details

and when I refresh the browser I got error `Cannot GET /app/apache/1.0.2/details` because of this code:
```javascript
    if (parsedUrl.pathname.indexOf('.') !== -1) {
      logger(
        'Not rewriting',
        req.method,
        req.url,
        'because the path includes a dot (.) character.'
      );
      return next();
    }
```

it would be nice if the library include an option to disable this behavior.

**Comment by bripkens** [comment]
Hey @jcubic,

this middleware actually includes an option to do this:

https://github.com/bripkens/connect-history-api-fallback#disabledotrule

Cheers

Ben
