### ISSUE TITLE
The app don't serve static files when using disableDotRule options

### ISSUE THREAD

**Issue by jcubic** [bripkens/connect-history-api-fallback#28]
if you use disableDotRule option static files like js that contain a dot are not serve. I think that the code should, if option is set, check if the file is on the disk and if so call next().

**Comment by bripkens** [comment]
Do you have any proposal how this should be done? The problem is, that files could be mounted at different locations and served using a variety of common and hand-written middlewares.

**Comment by sasikumardr** [comment]
@bripkens Something like capturing static files as globs in options is feasible?

**Comment by jcubic** [comment]
I've fixed my issue using [rewrites](https://github.com/bripkens/connect-history-api-fallback#rewrites)

**Comment by bripkens** [comment]
> Something like capturing static files as globs/array in options is feasible?
> Or adding check for existence in disk before skipping rewrite.

Both sound like interesting approaches to me @sasikumardr. Are you willing to prototype something so that we can give it a try?

**Comment by sasikumardr** [comment]
Something like this before dot rule check.
```
if (options.staticFiles && Array.isArray(options.staticFiles)) {
	for (var i=0; i< options.staticFiles.length; i++) {
		if(options.staticFiles[i] === parsedUrl) 
return next();
	}
}

//var fs = require('fs') at top of the source file
if (options.checkForFile && fs.existsSync(parsedUrl)) {
	//skip rewrite
	return next();
}
```

**Comment by bripkens** [comment]
Not sure whether this is necessary. What if we would do the following?

```
const staticFileMiddleware = express.static('./public');
app.use(staticFileMiddleware);
app.use(historyApiFallback());
app.use(staticFileMiddleware)
```

Wouldn't we achieve the same thing with less configuration duplication?

**Comment by sasikumardr** [comment]
This will work with disableDotRule? I think files will be served as index.html. Did not try this method though. 

I came across this issue in one of github [project] (https://github.com/mgechev/angular2-seed/issues/1269) and solved the issue by [rewrite rules] (https://github.com/mgechev/angular2-seed/commit/0069fda30fd383da96a034a178cbd422fc53bd10)

**Comment by vizo** [comment]
Anything new about this?

**Comment by bripkens** [comment]
I added a demo app which shows how to do this:

https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/static-files-and-index-rewrite

**Comment by mogusbi** [comment]
@jcubic Could you share the rewrite rule that fixed this issue for you?

**Comment by bripkens** [comment]
@mogusbi: Doesn't the previously posted example app help with your problem? If not, why? Trying to improve this so this becomes less confusing.

**Comment by jcubic** [comment]
@mogusbi I had urls like this `/custom-tabs/show/:name/details/:toolchain/:version/` and I use this rule:
```javascript
      historyApiFallback({
          rewrites: [
            // fix for dots in url disableDotRule: true don't work for static files
            { from: /custom-tabs\/show\/[^\/]+\/details\/[^\/]+\/[0-9.]+\//, to: '/index.html'}
          ]
      })
```

**Comment by mogusbi** [comment]
@bripkens I'm using this with browsersync for development rather than an express app so the example isn't applicable

@jcubic Thank you

I've got this working using this (it only works if all of your static assets live in a assets folder):

`
rewrites: [{
  from: /^(?!\/assets\/)/i,
  to: '/index.html'
}]
`
