### ISSUE TITLE
Invalid URL after second slash

### ISSUE THREAD

**Issue by huzjakd** [bripkens/connect-history-api-fallback#30]
If I enter URL like this: localhost:3000 it serves me index.html which is ok
If I enter URL localhost:3000/admin it serves me admin page which is ok
If I enter URL localhost:3000/invalidpage it serves me index.html again which is also ok
But if I enter localhost:3000/admin/invalidpage it tryes to get the invalid page, which is not ok.

So how do I set it up so that it serves index.html even after I enter invalid page after second "slash", or third etc.

**Comment by bripkens** [comment]
Without further information this is hard to say. Is your application available somewhere so that I can check this out? How is the middleware configured? How are the routes configured? How is the URL requested? What headers are used?

**Comment by huzjakd** [comment]
Unfortunately the app is still just on localhost.
In node.js it is set up like this:
var express = require('express');
var app = express();
var history = require('connect-history-api-fallback');
app.get('/admin', function (req, res) {
//returns admin page
//here I manually build the "endHtml" string and send it to the frontend with this:
res.end(endHtml, 'utf-8');
});
app.get('/', function (req, res) {
//returns index page
res.sendFile( "path/index.html" );
});
app.use(history());

I manually type localhost:3000/admin and it serves me the admin page. Than I manually add to the URL /someinvalidstring so the URL in the browser is: localhost:3000/admin/someinvalidstring
and this is what I get in my chrome console: http://prntscr.com/demxci

It might be important to note that I use vue.js and vue-router, but for admin page I don't use vue.js or vue-router. vue.js and vue-router are for localhost:3000 and localhost:3000/settings and localhost:3000/myapps. Those three routes are handled by vue-router, but not the admin page.
In vue-router I have this line of code which should redirect all invalid urls to home page (localhost:3000): routes.push({ path: "*", redirect: "/" });
Also from what I'm seeing in the console index.html get's called somehow because some .js and .css files that are called are located only on index.html, not on admin page.

**Comment by huzjakd** [comment]
One more thing. If I start node server and go directly to localhost:3000/myapps I get a page where it says: Cannot GET /myapps
But if I go first to localhost:3000 and it loads, and than type /myapps later, everything works fine

**Comment by bripkens** [comment]
You should generally use the middleware before your other route definitions and next to your static file middleware. Can you check out the example app and setup your project accordingly?

https://github.com/bripkens/connect-history-api-fallback/blob/master/examples/static-files-and-index-rewrite/index.js

**Comment by huzjakd** [comment]
I figured out what was the problem.
The module did redirect correctly to index.html everytime. But in the index.html I have stuff like: <script src="js/jquery-2.1.1.js"></script>
and if I navigated to localhost:3000/myapps/somethinginvalid it would serve index.html but the url for jquery file which would be requested next would be "myapps/js/jquery-2.1.1.js" instead "js/jquery-2.1.1.js", and off course it wouldn't find the jquery file. So in my index.html file I changed script and link tags to this format: <script src="../js/jquery-2.1.1.js"></script>
And now it server everything correctly.

**Comment by bripkens** [comment]
Sounds great! I'll close this then.

**Comment by huzjakd** [comment]
Just in case anyone else is interested:
<script src="../js/jquery-2.1.1.js"></script> doesn't work either. This just starts from one level above so for the URLs like localhost:3333/myapps/1 it works but not for localhost:3333/1/1/1/1/1... etc.
To really make it work it should be <script src="/js/jquery-2.1.1.js"></script> so it always starts from the root.

**Comment by misterigl** [comment]
thanks, I had the same problem with my Vue router
