### ISSUE TITLE
Add an option to ignore a set of paths

### ISSUE THREAD

**Issue by ripper234** [bripkens/connect-history-api-fallback#33]
I have a Singel Page App that issues JSON requests, and would like to handle it all from the same node server. It would be neat if an option similar to `rewrites` could be add so this module would just not touch these routes.

**Comment by bripkens** [comment]
This is already supported when using proper `Content-Type` headers. Also see the example app, specifically [1].

[1] https://github.com/bripkens/connect-history-api-fallback/blob/master/examples/static-files-and-index-rewrite/assets/js/index.js#L4

**Comment by ripper234** [comment]
Cheers, thanks.

**Comment by morriq** [comment]
@bripkens I need to have https://github.com/graphql/graphiql under my localhost:8080/graphql path. How can I achive that without operating in paths?

**Comment by bripkens** [comment]
@morriq: I don't understand how this is a problem of this middleware? If it is a problem, please provide more information and open a new issue.
