### ISSUE TITLE
How can i redirect this req to my declare path?

### ISSUE THREAD

**Issue by MrKou47** [bripkens/connect-history-api-fallback#35]
Hello , I have some problem from useing this middleware.
there is my folder: 

```
|-statics
   |-js
      |-vender.js
|-server
   |-router
   |-views
       |-index.html
|-server.js
```
there is my server.js: 

```js
const express = require('express');
const path = require('path');
const history = require('connect-history-api-fallback');
const proxy = require('express-http-proxy');

const env = process.env.NODE_ENV;
const isDeveloping = (process.env.NODE_ENV != 'production');

const port = isDeveloping ? 8000 : process.env.PORT;

const app = express();
app.use('/statics', express.static('statics'));
app.use(express.static('statics'));
app.all('/api/*', proxy('http://api.ilovelook.cn'));


// i think this middleware redirect req to get '/statics/' path .
// beasuse when i move 'index.html' into 'statics' , it work right
// so my answer is how to fix this problem?
app.use(history({
    index: './server/views/index.html',
    verbose: true
}));

app.listen(port, function onStart(err) {

    if (err) {
        console.log(err);
    }
    console.info(`Listening on port ${port}. Open up http://localhost:${port}/ in your browser.`);
});

```

**Comment by bripkens** [comment]
The `index` file you can specify via `history({index: '…'})` is not a file system path. Instead, it is the request path the server will see when the middleware decides to rewrite the path.

Did you check out the example app?

https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/static-files-and-index-rewrite

**Comment by MrKou47** [comment]
@bripkens 
oh, i add `app.use(express.static('server/view'));` behind use `history middleware`,it works great.
thx!

**Comment by bripkens** [comment]
Glad to hear this! :)

**Comment by MrKou47** [comment]
and this middleware just redirect view's route to request a statics file.   isn't right?

**Comment by bripkens** [comment]
Not quite, this middleware changes the request URL. What happens with that request is up to your application:

https://github.com/bripkens/connect-history-api-fallback/blob/master/lib/index.js#L72
