### ISSUE TITLE
Is there an order in resolving rules ?

### ISSUE THREAD

**Issue by moimael** [bripkens/connect-history-api-fallback#37]
Hi,

I'm trying to get this to work with react dev server. I have my landing pages under the `/` path and I want everything to be rewritten to `landing-pages.html` except if a more specific rule follows. For example if i have a rule to rewrite `/admin` to `admin.html`, I want it to take precedence over the `/` rule.

Currently I manage to get one or another, but not both working at the same time.
Thanks !

**Comment by bripkens** [comment]
Hi @moimael,

you can use the [rewrite](https://github.com/bripkens/connect-history-api-fallback#rewrites) option to accomplish this. Note that this requires you to manually specify the `/admin` rule. `connect-history-api-fallback` has no mechanism to inspect express (or similar) handler chains.
