### ISSUE TITLE
Fallback to closest index.html

### ISSUE THREAD

**Issue by htfy96** [bripkens/connect-history-api-fallback#39]
Hi,
I'm developing a website containing multiple SPAs along some static files in single project. The directory structure is as follows:
```
/
|- /SPA1
|   |--- index.html
|
|- index.html
|- foobar.html
```

I want to serve all `/foo/bar` with `index.html` and `/SPA1/foo/bar` with `SPA1/index.html`. Is there any way to achieve this?

**Comment by bripkens** [comment]
You might be able to achieve this by mounting multiple instances of this middleware under different paths, but I have never tried this.

**Comment by htfy96** [comment]
Thanks for reply. Finally I specified multiple `rewrites`:
```
app.use(require('connect-history-api-fallback')({
  rewrites: [{
    from: /\/SPA1\//,
    to: '/SPA1/index.html'
  },
  {
    from: /\/SPA2\//,
    to: '/SPA2/index.html'
  }]
}))
```
