### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by hackingbeauty** [bripkens/connect-history-api-fallback#40]
Hello, I'm using "connect-history-api-fallback" with webpack-dev-middleware.

I noticed that with multiple parts in a route (/user/12345), I'm getting an "Unexpected token <" error.  There is no error when the route has only one part (/user).

Here is a public gist for my server set up: https://gist.github.com/hackingbeauty/3654f5dae04abf9aa480d2823cc5e184

Is there any way I can patch this?

**Comment by zuobaojing** [comment]
@hackingbeauty seems you need to pass in htmlAcceptHeaders as well
```
{
  disableDotRule: true,
  htmlAcceptHeaders: ['text/html', 'application/xhtml+xml']
}
```

**Comment by hackingbeauty** [comment]
There was an issue with my Webpack config.  Thank you replying.
