### ISSUE TITLE
error 404 when refreshing page

### ISSUE THREAD

**Issue by ianrussel** [bripkens/connect-history-api-fallback#43]
Hello, I have this error when I refresh page

  localhost:9000 -> 404
localhost:9000/path1 -> 404
..etc

I set up my express js like this

app.js
   
         const history = require('connect-history-api-fallback');
         const connect = require('connect');

         app.use(history());

This is my router setup(vuejs)

       `import VueRouter from 'vue-router';

       import AddVue from '../components/code/addVue';
       import Code from '../components/code/Code';
       import Home from '../components/code/Home';
       import Google from '../components/code/Google';

      Vue.use(VueRouter);

      const NotFound = { template: '<div>Ariba Ariba Ariba Not Found</div>' }
      //const Google = { template: '<div> <h1>Google </h1></div>'}
      const routes = [
      {
          path: '/',
          name: 'Home',
          component: Home
      },
     {
         path: '/addVue',
         component: AddVue
         //beforeEnter: Auth.requireAuth
     },
     {
         path: '/puta/:name',
         component: Code
     },
     {
         path: '/google',
         component: Google
     },
     {
         path: '*',
         component: NotFound
     }
    ]
    const router = new VueRouter({
      mode: 'history',
       routes
    });

    export default router`

Any idea to solve this?

**Comment by bripkens** [comment]
You could start by setting the log level to verbose and seeing what the history API fallback is doing. I am pretty certain that this is not a problem with the history API fallback:

https://github.com/bripkens/connect-history-api-fallback#verbose
