### ISSUE TITLE
Serve different index.html for subdomain

### ISSUE THREAD

**Issue by VladShcherbin** [bripkens/connect-history-api-fallback#44]
Hey, I'm using webpack-dev-server with history api to serve pages. By default, it gives `index.html` and I want to make it work this way:

```txt
url -> given file

localhost:4000 -> index.html
admin.localhost:4000 -> admin.html
```

I was able to serve different page for different `pathname`, but can't make it work for a subdomain. Is it somehow possible?

**Comment by bripkens** [comment]
Hi,

this is not yet possible as the `context` object which is available for rewrites [1] does not provide access to the HTTP host header.

[1] https://github.com/bripkens/connect-history-api-fallback#rewrites

**Comment by VladShcherbin** [comment]
@bripkens maybe `index` can be used somehow like this:

```js
history({
  index: (req) => {
    return req.headers.host === 'admin.localhost:4000' ? '/admin.html' : '/index.html'
  }
})
```

**Comment by bripkens** [comment]
TBH when you have reached this stage, then you can probably use a custom middleware. I am open to extending the context object, but anything beyond this I am considering out of scope right now.

**Comment by VladShcherbin** [comment]
@bripkens hm, maybe it's possible to add `req` object to context [here](https://github.com/bripkens/connect-history-api-fallback/blob/master/lib/index.js#L87) so it can be accessed from 'to' function?

**Comment by VladShcherbin** [comment]
Some kind of this, if it will work:

```js
history({
  rewrites: [
    {
      from: /\//,
      to: function(context) {
        return context.req.headers.host === 'admin.localhost:4000'
          ? '/admin.html'
          : '/index.html'
      }
    }
  ]
})
```

**Comment by bripkens** [comment]
That I would be willing to accept a PR for ;)

**Comment by VladShcherbin** [comment]
@bripkens I actually tried this one before, but had a problem.

```js
rewrites: [
  {
    from: /./,
    to: function(context) {
      return '/admin.html'
    }
  }
]
```

With this config, I expect all url's to server `admin.html`. Pages like `/some` show `admin.html`, but the index route (`/`) still shows `index.html`.

Maybe I need to change the regex pattern or `index` overrides `/` path?

**Comment by VladShcherbin** [comment]
@bripkens nah, it's a side-effect of `webpack-dev-server`, it gives static files from `contentBase` folder before resolving history api. I'll try to somehow cheat it.

**Comment by VladShcherbin** [comment]
Yes, I can make it work with `req` in `context`. I'll send a PR.

**Comment by AlexSolovev** [comment]
> @bripkens I actually tried this one before, but had a problem.
> 
> ```js
> rewrites: [
>   {
>     from: /./,
>     to: function(context) {
>       return '/admin.html'
>     }
>   }
> ]
> ```
> 
> With this config, I expect all urls to serve `admin.html`. Pages like `/some` show `admin.html`, but the index route (`/`) still shows `index.html`.
> 
> Maybe I need to change the regex pattern or `index` overrides `/` path?

Did you resolve the issue? Could you explain, how to serve different index for `/`?
