### ISSUE TITLE
Exceptions for particular routes

### ISSUE THREAD

**Issue by ramazan793** [bripkens/connect-history-api-fallback#47]
How to not rewrite particular routes like `/auth/google`? 
Is there a way to add own exclusion for some routes? 

My temporary solution - use history only for specified routes, not for all app like `app.use(history)`

**Comment by superevanzhu** [comment]
I also want know that.

**Comment by bripkens** [comment]
The result of calling:

```
history({
  rewrites: [
    { from: /\/soccer/, to: '/soccer.html'}
  ]
})
```

is just a function of the form `(req, res, next) => void`. You can create a wrapper around history to achieve what you want. Adding exception support is out of scope for this module.

**Comment by nyngwang** [comment]
To @ramazan793 @superzw:

Hi, I know it's probably too late, but it's achievable :)

```js
historyApiFallback: {
  verbose: true,
  rewrites: [
    { from: /^\/(public|build)\//, to: context => context.parsedUrl.pathname },
    { from: /^(?!\/(public|build)\/)/, to: '/' },
  ]
},
```

This way, only those URL starting with `^/public/.*` or `^/build/.*` will be **excluded** from redirecting to `/`. This is my log using `webpack-dev-server`:

```
Rewriting GET /buisdlfusdf to /
Rewriting GET /test to /
Rewriting GET /public/css/ to /public/css/
Rewriting GET /build/vendors/ to /build/vendors/
```
