### ISSUE TITLE
Redirection causes download for SHTML-files

### ISSUE THREAD

**Issue by DonGissel** [bripkens/connect-history-api-fallback#49]
If using middleware that performs serverside-parsing of the target file (say, `index.shtml`), the file in question will just be downloaded, instead of parsed and served as I would've expected and/or hoped.

A middleware setup like this for BrowserSync:

```
const browserSyncSSI = require('browsersync-ssi');
const historyFallback = require('connect-history-api-fallback');

browserSyncConfig.server.middleware = [
    browserSyncSSI({
        baseDir: basePath,
        ext: '.shtml',
        version: '1.4.0'
    })),
    historyFallback({ index: "/index.shtml" }))
];
// and so on and so forth...
```

... will just result in me getting the raw file instead of the parsed one, and by forced download at that. I do realize the trouble and potential loops-of-death of getting the script to basically ask the localhost for a "parsed" version instead of the raw file (if there aren't better methods?), but it would greatly enhance the usability of this module. I am using SHTML for HTML scaffolding when a content delivery service has yet to be established, and being able to redirect to a pre-parsed version of the code would be a lot better than having to maintain two files (a pre-compiled version for this module to digest, and the actual SHTML-file), or just doing everything in plain HTML instead.

So, consider this a "what do I do"-request. Is there a way of getting hold of the pre-parsed version, without compiling it myself in some way?

**Comment by bripkens** [comment]
This usage question is unrelated to this project. Please consider opening a question on something like stackoverflow.

**Comment by DonGissel** [comment]
Unless this is a bug that the plugin might be able to circumvent – in that case it's actually a feature request. But sure.
