### ISSUE TITLE
How to handle multi level routes? e.g. /foo/bar - /foo/bar/baz etc

### ISSUE THREAD

**Issue by htasha** [bripkens/connect-history-api-fallback#53]
I've been trying to get my head around this but I couldn't find a way to do it, I'm using Vuejs for the client and I have a few routes `/foo, /foo/bar, /foo/bar/baz` the first route `/foo` works perfectly with this setup:

```
const express = require("express");
const app = express();
const history = require("connect-history-api-fallback");

app.use(history({ verbose: true }))
app.use(express.static("dist"));
app.listen(8080, "192.168.0.103");
```
this is the output from the console when you request `localhost:8080/`

```
Rewriting GET / to /index.html
Not rewriting GET /js/runtime.f7cf0276fe79edfd2f62.js because the path includes a dot (.) character.
Not rewriting GET /js/router.a0c4fca3337e1422cf49.js because the path includes a dot (.) character.
Not rewriting GET /js/vendor.387eab05f2364a6ef284.js because the path includes a dot (.) character.
Not rewriting GET /js/app.9bd5bbbb4614a89f1c6b.js because the path includes a dot (.) character.
```
those are the files from my build and untill now I have no problem with those files, so far so good. Now Vue has this thing where you have a catch-all route that renders a component if none of the routes match by doing this:

```
{
    path: "*",
    component: () => import(/* webpackChunkName: '404' */ "../components/404.vue")
}
```
so, for example if you type/go/refresh `localhost:8080/fou` the history middleware redirects back to `/` and when the scripts are loaded, Vue say, Hey! I don't know this path I'll render the `404` component instead, that's fine Vue will render the component. I don't actually know how Vue do this: store `/fou` route somewhere to be aware of after the server has sent the index.html.

The problem comes when I type/go/refresh for example `localhost:8080/foo/bar` whether or not these route exists in my Vue router I get a `404` only from the script you see above, it perfectly renders the `index.html` but none of these files and because the content of this particular route depends on those files I see nothing.

![files1](https://user-images.githubusercontent.com/37009121/42543029-dc2d1a14-8477-11e8-97aa-4bcc893c9d90.png)
![files2console](https://user-images.githubusercontent.com/37009121/42543032-de760ede-8477-11e8-9d3c-bdf57d23e66d.png)

It says: `refused to execute script because its MIME type ('text/html')` so I went and add to my config its MIME type to: `htmlAcceptHeaders: ['text/javascript', 'application/javascript']` and now there is no errors in the console and I get this instead: `Cannot GET /foo/bar` not only this I cannot go to `localhost:8080/foo` either but I can go to `localhost:8080/` just fine.

Then I tried:
```
app.use(
  history({ htmlAcceptHeaders: ["text/javascript", "application/javascript"] })
);
app.use(express.static("dist"));
app.use(
  history({
    verbose: true,
    rewrites: [
      {
        from: /^\/(.*)\/(.*)\/?$/i,
        to: context => {
          let path = context.parsedUrl.pathname.replace("/foo", "");
          return `./dist${path}`;
        }
      }
    ]
  })
);
```
and I get the same result. Does anybody knows how to properly get this middleware working? it is has to do with my webpack config? or I'm doing it wrong? I searched a lot on how to solve this from various sources and even different frameworks before I come here and I just cannot get it to work with express, I also post it in the Vue forum with no answer. I'll appreciate any help on this.

This is my distribution folder if helps
![dist](https://user-images.githubusercontent.com/37009121/42543623-ab0fc01e-847a-11e8-89e6-bd3ee3e639ce.png)

**Comment by bripkens** [comment]
Hey @htasha,

this is a bunch of information and based on a quick read, the most probable cause is a combination of HTTP request `Accept` headers I would say. I

This being said, I have no capacity to provide usage support. Please ask usage questions on Stackoverflow.

**Comment by htasha** [comment]
🙄
