### ISSUE TITLE
Rerouting insecure requests with express

### ISSUE THREAD

**Issue by brokyo** [bripkens/connect-history-api-fallback#54]
This is less of a bug and more that I'm just trying to understand best practices with the package. Currently I'm using this with a fairly simple express server that serves up a Webpacked Vue SPA. 

My server could be abstracted to look like this:

```
// Dependencies
var path = require('path')
var http = require('http')
var https = require('https')
var server = require('express').express()

// Attach middlware
server.use(history())

// Create servers and listen for requests
http.createServer(server).listen()
https.createServer(sslCert, server).listen()

// Redirect requests to https
server.use(function(req, res, next) {  
  if(req.secure || process.env.NODE_ENV == 'dev') {
    next()
  } else {
      res.redirect('https://' + req.headers.host + req.url);
    }
})  

// serve client directory
server.use(express.static(path.join(__dirname, '../client/dist')))
```

This works in every case other than one in which I enter `http://[hostname]` into the browser. 
`http://[hostname]` is passed to the `else` statement in the `Redirect requests to https` block and the `req.url` is `/index.html` resulting in `http://[hostname]/index.html`

Currently I'm just hacking around this by checking if `req.url == '/index.html'` and, if so, redirecting to the `https://[hostname]` but it feels like that can't be the best solution. Is there an option somewhere I'm missing or a better approach to this generally? Everything is working as expected I just feel like I'm missing a piece of information.

Thanks for the package, generally! So easy to use and has saved me so much time <3

**Comment by brokyo** [comment]
Yikes. Looks like this was already in there and I just didn't read the docs as thoroughly as I thought :/

Leaving this in the event it's useful to someone else. You can handle this case by using [rewrites](https://github.com/bripkens/connect-history-api-fallback#rewrites) and just checking for the /index.html string.

That is: my middleware should look more like this:
```
server.use(history({
  rewrites: [
    { from: '(\/index.html)', to: '/'}
  ]
}))
```

All good now! Thanks again for the package.

**Comment by brokyo** [comment]
Yikes. Looks like this was already in there and I just didn't read the docs as thoroughly as I thought :/

Leaving this in the event it's useful to someone else. You can handle this case by using [rewrites](https://github.com/bripkens/connect-history-api-fallback#rewrites) and just checking for the /index.html string.

That is: my middleware should look more like this:
```
server.use(history({
  rewrites: [
    { from: '(\/index.html)', to: '/'}
  ]
}))
```

All good now! Thanks again for the package.

**Comment by brokyo** [comment]
Sorry to reopen this but this actually isn't work as anticipated :/ 

The solution above only works when I manually enter `http://[host]/index.html/` into the browser - it doesn't work when I enter `http://[host]`. 

Any suggestions would be appreciated :)

**Comment by bripkens** [comment]
See this example app for best practices: https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/static-files-and-index-rewrite
