### ISSUE TITLE
How about use this lib in koa?

### ISSUE THREAD

**Issue by zgj233** [bripkens/connect-history-api-fallback#55]
Could give me some proposal about to use  ```connect-history-api-fallback```  in koa?

**Comment by bripkens** [comment]
Hey @zgj233,

the great @dalhorinek has forked this lib to provide a koa variant for it:

https://github.com/dalhorinek/koa-history-api-fallback

**Comment by zgj233** [comment]
> Hey @zgj233,
> 
> the great @dalhorinek has forked this lib to provide a koa variant for it:
> 
> https://github.com/dalhorinek/koa-history-api-fallback

thanks，sir
