### ISSUE TITLE
Doesn't work when a route is reloaded

### ISSUE THREAD

**Issue by georgeben** [bripkens/connect-history-api-fallback#61]
I set up a simple express app to use connect-history-api-fallback. Here's my code:

```js
const express = require('express');
const history = require('connect-history-api-fallback');
const PORT = process.env.PORT || 3000;
const path = require('path');
//Set my public folder to the dist folder
const public_dir  = path.resolve(__dirname, "dist");

const app = express();

app.use(express.static(public_dir));

app.use(history());

app.listen(PORT, () => console.log(`App started on port ${PORT}`))

```
I have a vue application which has a route - `/about` to display the about page.
When loaded initially in the browser, the routes work as expected but whenever I reload a route in my vue app, for example '/about', I get a `Cannot GET /about` which means a request was still sent to the server.

Please how can I solve this? Thank you.

**Comment by bripkens** [comment]
Check out the example app [1]. For follow up support please refer to StackOverflow.

[1] https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/static-files-and-index-rewrite
