### ISSUE TITLE
What if the index.html is not in the root directory,such as it's in the src directory?

### ISSUE THREAD

**Issue by hyq2015** [bripkens/connect-history-api-fallback#62]
below setting not work!!! seems it dosen't support directory 
app.use(history({
    index: path.resolve(__dirname,"../src/index.html")
}));

**Comment by bripkens** [comment]
The configuration files describes how the **HTTP** request path should be changed. I extended the documentation to make this more explicit. This will hopefully resolve the confusion for you:

https://github.com/bripkens/connect-history-api-fallback/blob/master/README.md#index
