### ISSUE TITLE
mistakenly rewriting non extension files as extensioned files

### ISSUE THREAD

**Issue by aminnaggar** [bripkens/connect-history-api-fallback#71]
It seems that regardless of what I set `disableDotRule` to it disables the dot rule. By that I mean that if a route does not have an extension it still treats it like it's a file and does not route it to index.html as it should but instead attempts to route the file.

I'm sure I'm missing something small, please let me know what it is I'm missing.

This is my current setup

```javascript
import path from 'path';
import history from 'connect-history-api-fallback';
import { static as expressStatic } from 'express';

const staticBaseRoute = '/public';
const staticFilePath= path.join(__dirname, '..', '/public/dist/');

app.use(
  history({
    verbose: true,
    index: path.join(staticBaseRoute, '/index.html'),
    disableDotRule: false,
    rewrites: [
      {
        from: /^\/(?!api\/).*/i,
        to(context) {
          const { pathname: pathName } = context.parsedUrl;

          const resultPath = path.join(staticBaseRoute, pathName);

          console.log(
            `HISTORY: routing from\n${pathName}\nto\n${resultPath}`,
          );
          return resultPath;
        },
      },
    ],
  }),
);

app.use(staticBaseRoute, expressStatic(staticFilePath));
```

### expected behaviour

- `/` -> `/public/index.html` -> `${__dirname}/../public/dist/index.html`
- `/login` -> `/public/index.html` -> `${__dirname}/../public/dist/index.html`
- `/css/main.css` -> `/public/css/main.css` -> `${__dirname}/../public/dist/css/main.css`
- `/api/users/:id` -> express route

### actual behaviour

-  ✅ `/` -> `/public/index.html` -> `${__dirname}/../public/dist/index.html`
-  🚫 `/login` -> `/public/index.html` -> `${__dirname}/../public/dist/index.html`
-  ✅ `/css/main.css` -> `/public/css/main.css` -> `${__dirname}/../public/dist/css/main.css`
- ✅ `/api/users/:id` -> express route

**Comment by bripkens** [comment]
Please check the example app and specifically how it mounts the static file handler (it does so twice). Does this resolve your problem?

https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/static-files-and-index-rewrite

**Comment by aminnaggar** [comment]
wow, thank you for the fast response checking it out now will let you know

**Comment by aminnaggar** [comment]
I'm afraid it's not working, I tried a bunch of different experiments but none of them gave me the desired effect.

Despite getting closer now the issue is that it correctly routes 

`/login` -> `/public/index.html` -> `${__dirname}/../public/dist/index.html`

however inside of my `index.html` it's referring to `/css/main.css`  which should redirect to `/public/css/main.css` which serves `/public/dist/css/main.css` but instead I get a **404**

**Comment by aminnaggar** [comment]
I used heavy inspiration from your code and wrote this:


```javascript
  /**
   * all non `/api/*` or `/public/*` routes should be rewritten
   * to `/public/*`
   */
  app.use((req, res, next) => {
    if (
      req.method !== 'GET' ||
      !/^\/(?!api\/|public\/).*/i.test(req.originalUrl)
    )
      return next();

    const rewriteTarget = path.join(staticBaseRoute, req.originalUrl);
    logger.debug('Rewriting', req.method, req.url, 'to', rewriteTarget);
    req.url = rewriteTarget;
    return next();
  });

  /**
   * all `/public/*` routes that don't have an extension
   * should be routed to `/public/` aka `/public/index.html`
   */
  app.use((req, res, next) => {
    if (req.method !== 'GET' || !/^\/public\/.*/i.test(req.url)) return next();

    if (path.extname(req.url)) {
      logger.debug(
        'Not rewriting',
        req.method,
        req.url,
        'because the path includes a dot (.) character.',
      );
      return next();
    }

    logger.debug(`Rewriting public non extension route to ${staticBaseRoute}`);
    req.url = path.join(staticBaseRoute, 'index.html');
    return next();
  });

  /**
   * attempt to serve `/public/*` routes statically
   * from `/public/dist/*`
   */
  app.use(staticBaseRoute, staticExpress(staticFilePath));
```

which behaves exactly as expected. I hope this helps.

I'm not sure if I should keep the ticket open or not, I'll leave that up to you. Let me know if you need any help with this implementation 👍

**Comment by bripkens** [comment]
Thanks!
