### ISSUE TITLE
hisotryApiFallback rewrites don't work

### ISSUE THREAD

**Issue by gapsaras** [bripkens/connect-history-api-fallback#75]
Hi there, recently I met a problem with rewrites, following is my config:
```
historyApiFallback: {
      rewrites: [
        { from: /^\/$/, to: '/index' },
      ],
    },
```

I want to rewrite path / to another appointed path `/index`, and other path fallback to default index.html， but fails, and I try with `curl` ,  when I `curl localhost:3031/` it returns the default index.html content, but `curl localhost:3031/index` it returns what I want.

Please let me how to fix it or is there a workaround way ?

**Comment by bripkens** [comment]
Hey @gapsaras,

this issue tracker is only meant to be used for bugs and feature requests. I interpret your message as a usage question. Please use platforms such as StackOverflow and others for usage questions.

This being said, I would suggest using the [verbose mode](https://github.com/bripkens/connect-history-api-fallback#verbose) to understand what connect-history-api-fallback is doing.
