### ISSUE TITLE
Dynamic content in index.html

### ISSUE THREAD

**Issue by chunkbro** [bripkens/connect-history-api-fallback#76]
I am using transformer-proxy module to load and edit value in index.html on startup. I see that with index property we can override the default index.html and it accepts a file name. Is there a way to pass html content to index property?

**Comment by Eduardo-Julio** [comment]
> I am using transformer-proxy module to load and edit value in index.html on startup. I see that with index property we can override the default index.html and it accepts a file name. Is there a way to pass html content to index property?

Did you find a solution for this?

**Comment by Eduardo-Julio** [comment]
Found a solution.

Commenting here in case its useful or anyone else:

Use the `index` property that you can set to the middleware to use a route as the fallback. 

Define that route and make all the logic to call and modify the index.html inside that route.

```
spaApp.use(historyApiFallback({
    index: "/other",
    verbose: true
}))

spaApp.get('/other', (req, res) => {
     // Custon logic to serve the index
    res.render('index'|)
})
```

**Comment by chunkbro** [comment]
> > I am using transformer-proxy module to load and edit value in index.html on startup. I see that with index property we can override the default index.html and it accepts a file name. Is there a way to pass html content to index property?
> 
> Did you found a solution for this?

I only needed one region specific property set dynamically. So I ended up saving the property in index.html before it is served. Your solution above should work better.
