### ISSUE TITLE
npm warning

### ISSUE THREAD

**Issue by cjmyles** [bripkens/connect-history-api-fallback#8]
When I install npm packages I'm now seeing the following warnings:
```
npm WARN unmet dependency [src dir]/node_modules/browser-sync/node_modules/browser-sync-ui requires connect-history-api-fallback@'0.0.5' but will load
npm WARN unmet dependency [src dir]/node_modules/connect-history-api-fallback
```
I'm assuming this is because of the work we did?

**Comment by bripkens** [comment]
Does this happen because of too incompatible versions, i.e. `0.0.5` and `1.0.0`?

**Comment by cjmyles** [comment]
I wondered if it was because it couldn't find 0.0.5? Because the module will download 0.0.5 which wouldn't have the breaking changes?

I'm not on the list of contributors here :(
https://www.npmjs.com/package/connect-history-api-fallback

**Comment by bripkens** [comment]
You associated an unknown email address, i.e. unknown to GitHub and npmjs, to your contributions. See here: https://github.com/bripkens/connect-history-api-fallback/commit/3f7249428a35ddc7dcee30bbfd251d3d9efd2353

**Comment by cjmyles** [comment]
Ah well spotted. I have my work email address configured for all my commits. I've changed it now for this repo but it will only take effect on new commits!

**Comment by bripkens** [comment]
Looks like this can be closed.
