### ISSUE TITLE
Running code from another path causes history api not to work

### ISSUE THREAD

**Issue by TarikSeyceri** [bripkens/connect-history-api-fallback#83]
Hello,

My project is in this path: /opt/backend/main.js
if i "cd /opt/backend" and "node main.js"
it works like a charm

but if i do this "cd /opt" and "node backend/main.js"
history api doesn't work, doesn't work, i meant: the request falls in my express.js 404 error
any idea to provide real __dirname to the history api ?

If you wanna ask me, why i wanna do this? it is because, i am using systemctl to run the project in the background, but i gave a simple example to explain the problem to you guys.

Thank you.

**Comment by bripkens** [comment]
Hey @TarikSeyceri,

this module does not leverage `__dirname` nor `process.cwd()`. So I would suspect that the problem you are facing does not reside within this module, but instead within a configuration of connect/express. In case you are using `express.static()`, I would suspect a relative directive reference as part of the [root argument](https://expressjs.com/en/4x/api.html#express.static).

**Comment by TarikSeyceri** [comment]
You are totally right!, it worked!!!, 

Thanks a lot!, 

i added __dirname to express.static(__dirname + "/public");

And it worked, Thanks again, you saved me a lot of trouble, sorry for the inconvenience.

Tarik.
